import turtle
turtle.color("green")
turtle.forward(100)
turtle.right(75)
turtle.forward(100)
turtle.right(75)
turtle.forward(100)
turtle.right(85)
turtle.forward(100)
turtle.right(50)
turtle.forward(68)
turtle.shape("turtle")
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.color("red")
turtle.begin_fill()
turtle.circle(50)
turtle.circle(51)
turtle.circle(53)
turtle.circle(54)
turtle.circle(55)
turtle.circle(56)
turtle.circle(57)
turtle.color("blue")
turtle.circle(58)
turtle.circle(59)
turtle.circle(60)
turtle.circle(61)
turtle.circle(62)
turtle.circle(63)
turtle.circle(64)
turtle.circle(65)
turtle.circle(66)
turtle.end_fill()
turtle.penup()
turtle.forward(100)
turtle.left(100)
turtle.forward(200)
turtle.pendown()
turtle.color("gold")
turtle.bgcolor("black")
turtle.write("Grey")
turtle.penup()
turtle.forward(100)
turtle.pendown()
def square():
    for i in range(4):
        turtle.forward(100)
        turtle.right(90)
square()
def square (sidelength):
    for i in range(4):
        turtle.forward(sidelength)
        turtle.right(90)
square(75)
turtle.penup()
turtle.left(100)
turtle.forward(100)
turtle.forward(100)
turtle.forward(100)
turtle.pendown()
turtle.speed(7)
def star(turtle, size):
    for i in range (5):
        turtle.forward(size)
        turtle.right(144)

size=1
for i in range(30):
    star(turtle, size)
    size = size + 5
    turtle.forward(1)
    turtle.right(10)

turtle.forward(5)
turtle.penup()
turtle.forward(100)
turtle.forward(100)
turtle.left(100)
turtle.forward(100)
turtle.forward(100)
turtle.forward(100)
turtle.forward(100)
turtle.forward(100)
turtle.pendown()
def star(sidelength):
    for size in range(5):
        turtle.forward(sidelength)
        turtle.right(150)
        turtle.forward(100)


for i in range(75):
 star(100)
turtle.forward(65)
turtle.exitonclick()